# Generated by Django 6.0.3 on 2026-04-02 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorCorporateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'creator_corporate_types',
            },
        ),
        migrations.CreateModel(
            name='CustodianType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custodian_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'custodian_types',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Custodian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_status', models.CharField(blank=True, max_length=2, null=True)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('administrative_structure', models.TextField(blank=True, null=True)),
                ('collecting_policies', models.TextField(blank=True, null=True)),
                ('holdings', models.TextField(blank=True, null=True)),
                ('accessibility', models.TextField(blank=True, null=True)),
                ('services', models.TextField(blank=True, null=True)),
                ('created_by', models.IntegerField(default=1)),
                ('updated_by', models.IntegerField(default=1)),
                ('db_source', models.CharField(blank=True, max_length=255, null=True)),
                ('legacy_id', models.CharField(blank=True, max_length=255, null=True)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custodian_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.custodiantype')),
                ('group', models.ForeignKey(blank=True, db_column='group_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.group')),
            ],
            options={
                'db_table': 'custodians',
            },
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_type', models.CharField(blank=True, max_length=1, null=True)),
                ('residence', models.TextField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('legal_status', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_by', models.IntegerField(default=1)),
                ('updated_by', models.IntegerField(default=1)),
                ('db_source', models.CharField(blank=True, max_length=255, null=True)),
                ('legacy_id', models.CharField(blank=True, max_length=255, null=True)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator_corporate_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.creatorcorporatetype')),
                ('group', models.ForeignKey(blank=True, db_column='group_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.group')),
            ],
            options={
                'db_table': 'creators',
            },
        ),
        migrations.CreateModel(
            name='Fond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancestry', models.CharField(blank=True, max_length=255, null=True)),
                ('ancestry_depth', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField(default=0)),
                ('sequence_number', models.IntegerField(blank=True, null=True)),
                ('trashed', models.BooleanField(default=False)),
                ('trashed_ancestor_id', models.IntegerField(blank=True, null=True)),
                ('units_count', models.IntegerField(default=0)),
                ('name', models.TextField(blank=True, null=True)),
                ('fond_type', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('extent', models.TextField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('arrangement_note', models.TextField(blank=True, null=True)),
                ('related_materials', models.TextField(blank=True, null=True)),
                ('access_condition', models.TextField(blank=True, null=True)),
                ('access_condition_note', models.TextField(blank=True, null=True)),
                ('use_condition', models.CharField(blank=True, max_length=255, null=True)),
                ('use_condition_note', models.TextField(blank=True, null=True)),
                ('type_materials', models.CharField(blank=True, max_length=255, null=True)),
                ('preservation', models.CharField(blank=True, max_length=255, null=True)),
                ('preservation_note', models.TextField(blank=True, null=True)),
                ('description_type', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_by', models.IntegerField(default=1)),
                ('updated_by', models.IntegerField(default=1)),
                ('db_source', models.CharField(blank=True, max_length=255, null=True)),
                ('legacy_id', models.CharField(blank=True, max_length=255, null=True)),
                ('legacy_parent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, db_column='group_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.group')),
            ],
            options={
                'db_table': 'fonds',
                'indexes': [models.Index(fields=['ancestry'], name='fonds_ancestr_f9ef00_idx'), models.Index(fields=['db_source', 'legacy_id'], name='fonds_db_sour_56eea9_idx')],
            },
        ),
    ]
