# Generated by Django 6.0.3 on 2026-04-02 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('sequence_number', models.IntegerField(blank=True, null=True)),
                ('ancestry', models.CharField(blank=True, max_length=255, null=True)),
                ('ancestry_depth', models.IntegerField(blank=True, null=True)),
                ('tsk', models.CharField(blank=True, max_length=5, null=True)),
                ('reference_number', models.TextField(blank=True, null=True)),
                ('tmp_reference_number', models.IntegerField(blank=True, null=True)),
                ('tmp_reference_string', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('given_title', models.BooleanField(blank=True, null=True)),
                ('folder_number', models.IntegerField(blank=True, null=True)),
                ('file_number', models.IntegerField(blank=True, null=True)),
                ('sort_letter', models.CharField(blank=True, max_length=255, null=True)),
                ('sort_number', models.IntegerField(blank=True, null=True)),
                ('unit_type', models.CharField(blank=True, max_length=255, null=True)),
                ('medium', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('arrangement_note', models.TextField(blank=True, null=True)),
                ('related_materials', models.TextField(blank=True, null=True)),
                ('physical_type', models.CharField(blank=True, max_length=255, null=True)),
                ('physical_description', models.TextField(blank=True, null=True)),
                ('physical_container_type', models.TextField(blank=True, null=True)),
                ('physical_container_title', models.TextField(blank=True, null=True)),
                ('physical_container_number', models.TextField(blank=True, null=True)),
                ('preservation', models.CharField(blank=True, max_length=255, null=True)),
                ('preservation_note', models.TextField(blank=True, null=True)),
                ('restoration', models.TextField(blank=True, null=True)),
                ('access_condition', models.CharField(blank=True, max_length=255, null=True)),
                ('access_condition_note', models.TextField(blank=True, null=True)),
                ('use_condition', models.CharField(blank=True, max_length=255, null=True)),
                ('use_condition_note', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('db_source', models.CharField(blank=True, max_length=255, null=True)),
                ('legacy_id', models.CharField(blank=True, max_length=255, null=True)),
                ('legacy_position', models.IntegerField(blank=True, null=True)),
                ('legacy_sequence_number', models.CharField(blank=True, max_length=255, null=True)),
                ('legacy_parent_unit_id', models.CharField(blank=True, max_length=255, null=True)),
                ('legacy_parent_fond_id', models.CharField(blank=True, max_length=255, null=True)),
                ('legacy_root_fond_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sc2_tsk', models.CharField(blank=True, max_length=10, null=True)),
                ('extent', models.TextField(blank=True, null=True)),
                ('published', models.BooleanField(default=True)),
                ('file_type', models.CharField(blank=True, max_length=255, null=True)),
                ('fsc_name', models.TextField(blank=True, null=True)),
                ('fsc_surname', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fond', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='archive.fond')),
                ('root_fond', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_units', to='archive.fond')),
            ],
            options={
                'db_table': 'units',
            },
        ),
    ]
