# Generated by Django 6.0.3 on 2026-04-02 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_unit'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('attachable_type', models.CharField(blank=True, max_length=255, null=True)),
                ('attachable_id', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_file_size', models.IntegerField(blank=True, null=True)),
                ('asset_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('db_source', models.CharField(blank=True, max_length=255, null=True)),
                ('legacy_id', models.CharField(blank=True, max_length=255, null=True)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('group', models.ForeignKey(blank=True, db_column='group_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.group')),
            ],
            options={
                'db_table': 'digital_objects',
            },
        ),
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_type', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('dates', models.CharField(blank=True, max_length=255, null=True)),
                ('qualifier', models.TextField(blank=True, null=True)),
                ('db_source', models.CharField(blank=True, max_length=255, null=True)),
                ('legacy_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, db_column='group_id', default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.group')),
            ],
            options={
                'db_table': 'headings',
            },
        ),
        migrations.CreateModel(
            name='RelCreatorFond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_source', models.CharField(blank=True, max_length=255, null=True)),
                ('legacy_creator_id', models.CharField(blank=True, max_length=255, null=True)),
                ('legacy_fond_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.creator')),
                ('fond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.fond')),
            ],
            options={
                'db_table': 'rel_creator_fonds',
            },
        ),
        migrations.CreateModel(
            name='RelCustodianFond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_source', models.CharField(blank=True, max_length=255, null=True)),
                ('legacy_custodian_id', models.CharField(blank=True, max_length=255, null=True)),
                ('legacy_fond_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custodian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.custodian')),
                ('fond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.fond')),
            ],
            options={
                'db_table': 'rel_custodian_fonds',
            },
        ),
        migrations.CreateModel(
            name='RelFondHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_source', models.CharField(blank=True, max_length=255, null=True)),
                ('legacy_fond_id', models.CharField(blank=True, max_length=255, null=True)),
                ('legacy_heading_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.fond')),
                ('heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.heading')),
            ],
            options={
                'db_table': 'rel_fond_headings',
            },
        ),
        migrations.CreateModel(
            name='RelUnitHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_source', models.CharField(blank=True, max_length=255, null=True)),
                ('legacy_unit_id', models.CharField(blank=True, max_length=255, null=True)),
                ('legacy_heading_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.heading')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.unit')),
            ],
            options={
                'db_table': 'rel_unit_headings',
            },
        ),
        migrations.AddIndex(
            model_name='heading',
            index=models.Index(fields=['name'], name='headings_name_35faa9_idx'),
        ),
        migrations.AddIndex(
            model_name='heading',
            index=models.Index(fields=['db_source', 'legacy_id'], name='headings_db_sour_f8bae1_idx'),
        ),
    ]
