# Generated by Django 6.0.3 on 2026-04-02 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_source_fond_parent_unit_parent_institution'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiogHist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('body', models.TextField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('db_source', models.CharField(blank=True, max_length=255, null=True)),
                ('legacy_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Biographical/Administrative History',
                'verbose_name_plural': 'Biographical/Administrative Histories',
                'db_table': 'biog_hists',
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, db_column='group_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.group')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='archive.classification')),
            ],
            options={
                'verbose_name_plural': 'classifications',
                'db_table': 'classifications',
            },
        ),
        migrations.AddField(
            model_name='unit',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='archive.classification'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('preferred', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=True)),
                ('event_type', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date_place', models.TextField(blank=True, null=True)),
                ('start_date_spec', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date_from', models.DateField(blank=True, null=True)),
                ('start_date_to', models.DateField(blank=True, null=True)),
                ('start_date_valid', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date_format', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date_display', models.CharField(blank=True, max_length=255, null=True)),
                ('end_date_place', models.TextField(blank=True, null=True)),
                ('end_date_spec', models.CharField(blank=True, max_length=255, null=True)),
                ('end_date_from', models.DateField(blank=True, null=True)),
                ('end_date_to', models.DateField(blank=True, null=True)),
                ('end_date_valid', models.CharField(blank=True, max_length=255, null=True)),
                ('end_date_format', models.CharField(blank=True, max_length=255, null=True)),
                ('end_date_display', models.CharField(blank=True, max_length=255, null=True)),
                ('legacy_display_date', models.CharField(blank=True, max_length=255, null=True)),
                ('order_date', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('db_source', models.CharField(blank=True, max_length=255, null=True)),
                ('legacy_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'events',
            },
        ),
    ]
