# Generated by Django 6.0.3 on 2026-04-02 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_bioghist_classification_unit_classification_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='IccdAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'iccd_authors',
            },
        ),
        migrations.CreateModel(
            name='IccdDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.CharField(blank=True, max_length=255, null=True)),
                ('object_type', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('age_century', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(blank=True, to='archive.iccdauthor')),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='iccd_card', to='archive.unit')),
            ],
            options={
                'verbose_name': 'Cultural Heritage Card (Iccd)',
                'db_table': 'iccd_descriptions',
            },
        ),
        migrations.CreateModel(
            name='Sc2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique', models.CharField(blank=True, max_length=255, null=True)),
                ('support', models.CharField(blank=True, max_length=255, null=True)),
                ('scale', models.CharField(blank=True, max_length=255, null=True)),
                ('preservation', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sc2_card', to='archive.unit')),
            ],
            options={
                'verbose_name': 'Technical Drawing Card (Sc2)',
                'db_table': 'sc2s',
            },
        ),
    ]
