# Generated by Django 6.0.3 on 2026-04-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_iccdauthor_iccddescription_sc2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sc2',
            name='note',
        ),
        migrations.RemoveField(
            model_name='sc2',
            name='preservation',
        ),
        migrations.RemoveField(
            model_name='sc2',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='sc2',
            name='support',
        ),
        migrations.RemoveField(
            model_name='sc2',
            name='technique',
        ),
        migrations.AddField(
            model_name='iccdauthor',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='Dati anagrafici/biografia'),
        ),
        migrations.AddField(
            model_name='sc2',
            name='dpgf',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Numero tavola'),
        ),
        migrations.AddField(
            model_name='sc2',
            name='lrc',
            field=models.TextField(blank=True, null=True, verbose_name='Luogo di rappresentazione'),
        ),
        migrations.AddField(
            model_name='sc2',
            name='misa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Altezza'),
        ),
        migrations.AddField(
            model_name='sc2',
            name='misl',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Larghezza'),
        ),
        migrations.AddField(
            model_name='sc2',
            name='mtce',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Esecuzione'),
        ),
        migrations.AddField(
            model_name='sc2',
            name='sca',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Scala'),
        ),
        migrations.AddField(
            model_name='sc2',
            name='sdtt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo di rappresentazione'),
        ),
        migrations.AddField(
            model_name='sc2',
            name='sgti',
            field=models.TextField(blank=True, null=True, verbose_name='Soggetto iconografico'),
        ),
    ]
