# Generated by Django 6.0.3 on 2026-04-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_remove_sc2_note_remove_sc2_preservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sc2',
            name='card_type',
            field=models.CharField(default='SC2', max_length=10),
        ),
    ]
