# Generated by Django 6.0.3 on 2026-04-02 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0009_lang_activity_anagraphic_anagidentifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fond',
            name='access_condition_term',
            field=models.ForeignKey(blank=True, db_column='access_condition_term_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fonds_by_access_condition', to='archive.term'),
        ),
        migrations.AddField(
            model_name='fond',
            name='description_type_term',
            field=models.ForeignKey(blank=True, db_column='description_type_term_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fonds_by_description_type', to='archive.term'),
        ),
        migrations.AddField(
            model_name='fond',
            name='fond_type_term',
            field=models.ForeignKey(blank=True, db_column='fond_type_term_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fonds_by_fond_type', to='archive.term'),
        ),
        migrations.AddField(
            model_name='fond',
            name='preservation_term',
            field=models.ForeignKey(blank=True, db_column='preservation_term_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fonds_by_preservation', to='archive.term'),
        ),
        migrations.AddField(
            model_name='fond',
            name='use_condition_term',
            field=models.ForeignKey(blank=True, db_column='use_condition_term_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fonds_by_use_condition', to='archive.term'),
        ),
        migrations.AddField(
            model_name='term',
            name='vocabulary',
            field=models.ForeignKey(blank=True, db_column='vocabulary_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='archive.vocabulary'),
        ),
        migrations.AddField(
            model_name='unit',
            name='access_condition_term',
            field=models.ForeignKey(blank=True, db_column='access_condition_term_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units_by_access_condition', to='archive.term'),
        ),
        migrations.AddField(
            model_name='unit',
            name='preservation_term',
            field=models.ForeignKey(blank=True, db_column='preservation_term_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units_by_preservation', to='archive.term'),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_type_term',
            field=models.ForeignKey(blank=True, db_column='unit_type_term_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units_by_unit_type', to='archive.term'),
        ),
        migrations.AddField(
            model_name='unit',
            name='use_condition_term',
            field=models.ForeignKey(blank=True, db_column='use_condition_term_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units_by_use_condition', to='archive.term'),
        ),
    ]
