# Generated by Django 6.0.3 on 2026-04-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0010_add_term_foreign_keys_for_standardized_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='term_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='term_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
