# Generated by Django 6.0.3 on 2026-04-02 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0011_add_term_key_and_position_to_term'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='place',
            name='places_db_sour_b58bf2_idx',
        ),
        migrations.RemoveField(
            model_name='lang',
            name='name_en',
        ),
        migrations.AddField(
            model_name='lang',
            name='db_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lang',
            name='legacy_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='digitalobject',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='digitalobject',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='lang',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AddIndex(
            model_name='creator',
            index=models.Index(fields=['db_source', 'legacy_id'], name='creators_db_sour_c2874f_idx'),
        ),
        migrations.AddIndex(
            model_name='custodian',
            index=models.Index(fields=['db_source', 'legacy_id'], name='custodians_db_sour_a2cd32_idx'),
        ),
        migrations.AddIndex(
            model_name='lang',
            index=models.Index(fields=['db_source', 'legacy_id'], name='langs_db_sour_22dcf6_idx'),
        ),
    ]
