# Generated by Django 6.0.3 on 2026-04-02 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0012_remove_place_places_db_sour_b58bf2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='medium_term',
            field=models.ForeignKey(blank=True, db_column='medium_term_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units_by_medium', to='archive.term'),
        ),
        migrations.AddField(
            model_name='unit',
            name='physical_type_term',
            field=models.ForeignKey(blank=True, db_column='physical_type_term_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units_by_physical_type', to='archive.term'),
        ),
    ]
