# Generated by Django 6.0.3 on 2026-04-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0013_add_physical_type_and_medium_terms_to_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sc2',
            name='cmmr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Numero di commessa'),
        ),
        migrations.AddField(
            model_name='sc2',
            name='lrd',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Data della ripresa'),
        ),
        migrations.AddField(
            model_name='sc2',
            name='ort',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Orientamento'),
        ),
        migrations.AddField(
            model_name='sc2',
            name='sdts',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rappresentazione tematica'),
        ),
    ]
