# Generated by Django 6.0.3 on 2026-04-03 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0014_add_sc2_extra_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.AddField(
            model_name='project',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type_term',
            field=models.ForeignKey(blank=True, db_column='project_type_term_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_types', to='archive.term'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status_term',
            field=models.ForeignKey(blank=True, db_column='status_term_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_statuses', to='archive.term'),
        ),
        migrations.AlterField(
            model_name='project',
            name='group',
            field=models.ForeignKey(blank=True, db_column='group_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.group'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='ProjectManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('qualifier', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_managers', to='archive.project')),
                ('qualifier_term', models.ForeignKey(blank=True, db_column='qualifier_term_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_manager_qualifiers', to='archive.term')),
            ],
            options={
                'db_table': 'project_managers',
            },
        ),
        migrations.CreateModel(
            name='ProjectStakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('qualifier', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_stakeholders', to='archive.project')),
                ('qualifier_term', models.ForeignKey(blank=True, db_column='qualifier_term_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_stakeholder_qualifiers', to='archive.term')),
            ],
            options={
                'db_table': 'project_stakeholders',
            },
        ),
        migrations.CreateModel(
            name='ProjectUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_urls', to='archive.project')),
            ],
            options={
                'db_table': 'project_urls',
                'ordering': ['position'],
            },
        ),
    ]
