# Generated by Django 6.0.3 on 2026-04-03 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0015_remove_project_end_date_remove_project_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sc2AttributionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autm', models.CharField(blank=True, max_length=255, null=True)),
                ('db_source', models.CharField(blank=True, max_length=255, null=True)),
                ('legacy_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sc2_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sc2_attribution_reasons', to='archive.sc2author')),
            ],
            options={
                'db_table': 'sc2_attribution_reasons',
                'indexes': [models.Index(fields=['db_source', 'legacy_id'], name='sc2_attribu_db_sour_9eadd6_idx')],
            },
        ),
    ]
