# Generated by Django 6.0.3 on 2026-04-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0016_add_sc2_attribution_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitotherreferencenumber',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unitotherreferencenumber',
            name='qualifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
