# Generated by Django 6.0.3 on 2026-04-04 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0017_add_unit_other_ref_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='abstract',
            field=models.TextField(blank=True, null=True, verbose_name='Abstract'),
        ),
        migrations.AddField(
            model_name='source',
            name='book_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='created_by',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='source',
            name='date_string',
            field=models.TextField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='source',
            name='db_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='finding_aid_published',
            field=models.BooleanField(blank=True, null=True, verbose_name='Strumento di corredo pubblicato'),
        ),
        migrations.AddField(
            model_name='source',
            name='finding_aid_valid',
            field=models.BooleanField(blank=True, null=True, verbose_name='Strumento di corredo valido'),
        ),
        migrations.AddField(
            model_name='source',
            name='group',
            field=models.ForeignKey(blank=True, db_column='group_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.group'),
        ),
        migrations.AddField(
            model_name='source',
            name='institution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='legacy_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='legacy_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='pages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='related_item',
            field=models.TextField(blank=True, null=True, verbose_name='Titolo libro correlato/rivista'),
        ),
        migrations.AddField(
            model_name='source',
            name='related_item_specs',
            field=models.TextField(blank=True, null=True, verbose_name='Specifiche elemento correlato'),
        ),
        migrations.AddField(
            model_name='source',
            name='updated_by',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='source',
            name='volume',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SourceUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_urls', to='archive.source')),
            ],
            options={
                'db_table': 'source_urls',
                'ordering': ['id'],
            },
        ),
    ]
