# Generated by Django 6.0.3 on 2026-04-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0018_add_source_extra_fields_and_source_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceType',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('source_type', models.CharField(max_length=255)),
                ('parent_code', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'source_types',
                'ordering': ['position'],
            },
        ),
    ]
