# Generated by Django 6.0.3 on 2026-04-05 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0019_add_source_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('qualifier', models.CharField(blank=True, max_length=255, null=True)),
                ('editing_type', models.CharField(blank=True, max_length=255, null=True)),
                ('edited_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_editors', to='archive.institution')),
            ],
            options={
                'db_table': 'institution_editors',
                'ordering': ['edited_at'],
            },
        ),
    ]
