# Generated by Django 6.0.3 on 2026-04-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0021_digital_object_nullable_gfk'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalobject',
            name='asset',
            field=models.FileField(blank=True, null=True, upload_to='digital_objects/%Y/%m/%d/'),
        ),
    ]
