# Generated by Django 6.0.3 on 2026-04-06 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0022_digital_object_asset_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('fond', 'Fondo'), ('unit', 'Unità'), ('creator', 'Soggetto produttore'), ('custodian', 'Soggetto conservatore'), ('source', 'Fonte'), ('project', 'Progetto'), ('heading', 'Voce di indice'), ('anagraphic', 'Anagrafica'), ('institution', 'Profilo istituzionale'), ('document_form', 'Profilo documentario'), ('classification', 'Classificazione')], max_length=50)),
                ('entity_id', models.IntegerField()),
                ('action', models.CharField(choices=[('create', 'Creazione'), ('update', 'Modifica'), ('delete', 'Eliminazione')], default='update', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Descrizione della modifica', null=True)),
                ('field_name', models.CharField(blank=True, help_text='Campo modificato', max_length=100, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editor_logs', to='archive.editor')),
            ],
            options={
                'db_table': 'editor_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='editor_logs_entity__edeac8_idx'), models.Index(fields=['editor'], name='editor_logs_editor__f535b0_idx')],
            },
        ),
    ]
