# Generated by Django 6.0.3 on 2026-04-07 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0024_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relcreatorfond',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_creator_fonds', to='archive.creator'),
        ),
        migrations.AlterField(
            model_name='relcreatorfond',
            name='fond',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_creator_fonds_fond', to='archive.fond'),
        ),
        migrations.AlterField(
            model_name='relcreatorinstitution',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_creator_institutions', to='archive.creator'),
        ),
        migrations.AlterField(
            model_name='relcreatorinstitution',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_creator_institutions', to='archive.institution'),
        ),
        migrations.AlterField(
            model_name='relcreatorsource',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_creator_sources', to='archive.creator'),
        ),
        migrations.AlterField(
            model_name='relcreatorsource',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_creator_sources', to='archive.source'),
        ),
        migrations.AlterField(
            model_name='relcustodianfond',
            name='custodian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_custodian_fonds', to='archive.custodian'),
        ),
        migrations.AlterField(
            model_name='relcustodianfond',
            name='fond',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_custodian_fonds_fond', to='archive.fond'),
        ),
        migrations.AlterField(
            model_name='relcustodiansource',
            name='custodian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_custodian_sources', to='archive.custodian'),
        ),
        migrations.AlterField(
            model_name='relcustodiansource',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_custodian_sources', to='archive.source'),
        ),
        migrations.AlterField(
            model_name='relfonddocumentform',
            name='document_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_fond_document_forms', to='archive.documentform'),
        ),
        migrations.AlterField(
            model_name='relfonddocumentform',
            name='fond',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_fond_document_forms', to='archive.fond'),
        ),
        migrations.AlterField(
            model_name='relfondheading',
            name='fond',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_fond_headings', to='archive.fond'),
        ),
        migrations.AlterField(
            model_name='relfondheading',
            name='heading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_fond_headings', to='archive.heading'),
        ),
        migrations.AlterField(
            model_name='relfondsource',
            name='fond',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_fond_sources', to='archive.fond'),
        ),
        migrations.AlterField(
            model_name='relfondsource',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_fond_sources', to='archive.source'),
        ),
        migrations.AlterField(
            model_name='relprojectfond',
            name='fond',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_project_fonds', to='archive.fond'),
        ),
        migrations.AlterField(
            model_name='relprojectfond',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_project_fonds', to='archive.project'),
        ),
        migrations.AlterField(
            model_name='relunitanagraphic',
            name='anagraphic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_unit_anagraphics', to='archive.anagraphic'),
        ),
        migrations.AlterField(
            model_name='relunitanagraphic',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_unit_anagraphics', to='archive.unit'),
        ),
        migrations.AlterField(
            model_name='relunitheading',
            name='heading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_unit_headings', to='archive.heading'),
        ),
        migrations.AlterField(
            model_name='relunitheading',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_unit_headings', to='archive.unit'),
        ),
        migrations.AlterField(
            model_name='relunitsource',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_unit_sources', to='archive.source'),
        ),
        migrations.AlterField(
            model_name='relunitsource',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_unit_sources', to='archive.unit'),
        ),
    ]
